# ddc plugins

# Core plugins {{{
[[plugins]] # pum.vim
repo = 'Shougo/pum.vim'
lua_source = '''
vim.fn['pum#set_option']({
  border = [[single]],
  -- scrollbar_char = [[┃]],
  max_width = 90,
})
'''

[[plugins]] # ddc-ui-pum
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]] # ddc.vim
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim', 'pum.vim', 'lexima.vim']
on_event = ['InsertEnter', 'CmdlineEnter', 'CursorHold', 'LspAttach']
hooks_file = '$HOOKS_DIR/ddc/hook.lua'

# }}}

# source plugins {{{
[[plugins]] # ddc-source-around
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]] # ddc-buffer
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-file
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-rg
repo = 'Shougo/ddc-source-rg'
on_source = 'ddc.vim'

[[plugins]] # neco-vim
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'toml', 'help']

[[plugins]] # ddc-source-lsp
repo = 'Shougo/ddc-source-lsp'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
on_source = 'ddc-source-lsp'
lua_source = '''
require("ddc_source_lsp_setup").setup()
'''

[[plugins]]
repo = 'uga-rosa/ddc-source-nvim-lua'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-line
repo = 'Shougo/ddc-source-line'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-cmdline
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-cmdline-history
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]] # ddc-source-input
repo = 'Shougo/ddc-source-input'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
depends = 'vim-vsnip'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'delphinus/ddc-shell-history'
on_source = 'ddc.vim'

# }}}

# filter plugins {{{
[[plugins]] # ddc-matcher_head
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]] # ddc-matcher_length
repo = 'Shougo/ddc-matcher_length'
on_source = 'ddc.vim'

[[plugins]] # ddc-sorter_rank
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]] # ddc-converter_remove_overlap
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]] # ddc-fuzzy
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

# }}}

# snippet plugins {{{
[[plugins]] # vim-vsnip
repo = 'hrsh7th/vim-vsnip'
hooks_file = '$HOOKS_DIR/vsnip.lua'

[[plugins]]
repo = 'uga-rosa/denippet.vim'
hooks_file = '$HOOKS_DIR/denippet.lua'
# }}}
