# ddu plugins
# Core plugins {{{
[[plugins]] # ddu.vim
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_func = 'ddu#start()'
on_cmd = 'DeinUpdate'
hooks_file = '$HOOKS_DIR/ddu/global.lua'

# }}}

# UI plugins {{{
[[plugins]] # ddu-ui-ff
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hooks_file = '$HOOKS_DIR/ddu/ff.lua'

[[plugins]] # ddu-ui-filer
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hooks_file = '$HOOKS_DIR/ddu/filer.lua'
# }}}

# Kind plugins {{{
[[plugins]] # ddu-kind-file
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]] # ddu-kind-word
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'

# }}}

# Source plugins {{{
[[plugins]] # ddu-source-file
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-file_rec
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-help
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]] # vim-readme-viewer
repo = '4513ECHO/vim-readme-viewer'
on_cmd = 'ReadmeOpen'
on_source = 'ddu.vim'
lua_add = '''
vim.g['readme_viewer#plugin_manager'] = [[dein.vim]]
'''

[[plugins]] # ddu-source-buffer
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-action
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-register
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-rg
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-mr
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-highlight'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-path_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-source-git_status'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-source-git_diff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-git_branch'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-git_log'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-source-git_diff_tree'
on_source = 'ddu.vim'

[[plugins]]
repo = '4513ECHO/ddu-source-ghq'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'

# }}}

# Filter plugins {{{
[[plugins]] # ddu-filter-matcher_substring
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_hidden
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_relative
repo = 'Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-filter-fuse'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-filter-converter_devicon'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Milly/ddu-filter-merge'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Milly/ddu-filter-kensaku'
depends = 'kensaku.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

# }}}

# Column plugins {{{
[[plugins]] # ddu-column-icon_filename
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# }}}
