[[plugins]] # Dark power plugin manager
repo = 'Shougo/dein.vim'

# [[plugins]] # Color scheme for editor
# repo = 'cocopon/iceberg.vim'

[[plugins]] # Japanese localization of help
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'mattn/learn-vimscript'

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
lua_add = '''
require('impatient').enable_profile()
'''

[[plugins]]
repo = 'delphinus/cellwidths.nvim'
lua_add = '''
require('cellwidths').setup {
  name = 'cica',
}
'''
