
[[plugins]] # dein.vim
repo = 'Shougo/dein.vim'
[[plugins]] # vimdoc-ja
repo = 'vim-jp/vimdoc-ja'
[[plugins]] # learn-vimscript
repo = 'mattn/learn-vimscript'

[[plugins]] # filetype.nvim
repo = 'nathom/filetype.nvim'

[[plugins]] # impatient.nvim
repo = 'lewis6991/impatient.nvim'
lua_add = '''
require('impatient').enable_profile()
'''

[[plugins]] # cellwidths.nvim (disable)
repo = 'delphinus/cellwidths.nvim'
if = 0
lua_add = '''
if vim.api.nvim_get_option('ambiwidth') == 'single' then
  local cellwidths_conf =  {
    name = 'user/cica',
    fallback = function(cw)
      cw.load 'cica'
      cw.add {
        {0xe0b2, 0xe0b3, 1},
        {0xeab5, 0xeab6, 4},
      }
    end,
  }
elseif vim.api.nvim_get_option('ambiwidth') == 'double' then
  local cellwidths_conf = { name ='cica' }
end
require('cellwidths').setup(cellwidths_conf)
'''

[[plugins]]
repo = 'lambdalisue/mr.vim'
