hooks_file = '$HOOKS_DIR/deinft.lua'

# Non-lazy plugins
[[plugins]] # dein.vim
repo = 'Shougo/dein.vim'

[[plugins]] # vimdoc-ja
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # learn-vimscript
repo = 'mattn/learn-vimscript'

[[plugins]] # mr.vim
repo = 'lambdalisue/mr.vim'
hooks_file = '$HOOKS_DIR/mr.lua'

[[plugins]]
repo = 'tani/vim-artemis'

[[plugins]] # nightfox.nvim
repo = 'EdenEast/nightfox.nvim'
hooks_file = '$HOOKS_DIR/nightfox.lua'
