# denops plugins
[[plugins]] # denops.vim
repo = 'vim-denops/denops.vim'
hook_add = '''
let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]] # skkeleton
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_map = { ic = '<Plug>(skkeleton-toggle)' }
build = 'bash $HOME/dotfiles/bin/skk_dict.sh'
hook_add = '''
imap <C-j> <Plug>(skkeleton-toggle)
cmap <C-j> <Plug>(skkeleton-toggle)
'''
hook_source = '''
augroup skkeleton_autocmds
  autocmd!
  autocmd User skkeleton-initialize-pre call vimrc#skkeleton_init()
  autocmd User skkeleton-enable-pre call vimrc#skkeleton_pre()
  autocmd User skkeleton-disable-pre call vimrc#skkeleton_post()
  autocmd InsertLeave * mode
augroup END
'''

[[plugins]] # lightline_skk.vim
repo = 'yasunori-kirin0418/lightline_skk.vim'
on_source = 'skkeleton'
hook_source = '''
call lightline_skk#option('display', {
\ 'hiragana': 'あぁ﫦',
\ 'katakana': 'アァ﫦',
\ 'hankaku-katakana': 'ｱｧ﫦',
\ 'zenkaku-alphabet': 'Ａａ﫦',
\ 'alphabet': 'Aa﫦',
\ })
'''

[[plugins]] # denops-translate.vim
repo = 'skanehira/denops-translate.vim'
depends = 'denops.vim'
on_cmd = 'Translate'
on_map = { 'nx' = '<Plug>(Translate' }
hook_add = '''
nmap tx <Plug>(Translate)
nmap tX <Plug>(Translate-reverse)
xmap tx <Plug>(Translate)
xmap tX <Plug>(Translate-reverse)
'''

[[plugins]] # denops-silicon.vim
repo = 'skanehira/denops-silicon.vim'
depends = 'denops.vim'
on_cmd = 'Silicon'
hook_source = '''
let g:silicon_options = {
  \ 'font': 'Cica',
  \ 'no_line_number': v:false,
  \ 'no_round_corner': v:false,
  \ 'no_window_controls': v:true,
  \ 'background_color': '#434C5E',
  \ 'line_offset': 1,
  \ 'line_pad': 2,
  \ 'pad_horiz': 80,
  \ 'pad_vert': 100,
  \ 'shadow_blur_radius': 20,
  \ 'shadow_color': '#2E3440',
  \ 'shadow_offset_x': 10,
  \ 'shadow_offset_y': 10,
  \ 'tab_width': &tabstop,
  \ 'theme': 'Nord',
  \ }
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = ['denops.vim', 'kensaku.vim']
on_cmd = ['FuzzyMotion']
hook_add = '''
nnoremap s/ <Cmd>FuzzyMotion<CR>
'''
hook_source = '''
let g:fuzzy_motion_auto_jump = v:true
let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
'''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'lambdalisue/kensaku-search.vim'
depends = 'kensaku.vim'
on_map = { 'c' = '<Plug>(kensaku-search-replace)' }
hook_add = '''
cnoremap <CR> <Plug>(kensaku-search-replace)<CR>
'''

[[plugins]]
repo = 'lambdalisue/askpass.vim'
depends = 'denops.vim'
