# denops plugins
[[plugins]] # denops.vim
repo = 'vim-denops/denops.vim'
hook_add = '''
let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]] # skkeleton
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_map = { ic = '<Plug>(skkeleton-toggle)' }
build = 'bash $HOME/dotfiles/bin/skk_dict.sh'
hooks_file = '~/.config/nvim/hooks/skkeleton.vim'

[[plugins]] # lightline_skk.vim
repo = 'yasunori-kirin0418/lightline_skk.vim'
on_source = 'skkeleton'
hooks_file = '~/.config/nvim/hooks/lightline_skk.vim'

[[plugins]] # denops-translate.vim
repo = 'skanehira/denops-translate.vim'
depends = 'denops.vim'
on_cmd = 'Translate'
on_map = { 'nx' = '<Plug>(Translate' }
hooks_file = '~/.config/nvim/hooks/translate.vim'

[[plugins]] # denops-silicon.vim
repo = 'skanehira/denops-silicon.vim'
depends = 'denops.vim'
on_cmd = 'Silicon'
hooks_file = '~/.config/nvim/hooks/silicon.lua'

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = ['denops.vim', 'kensaku.vim']
on_cmd = ['FuzzyMotion']
hook_add = '''
nnoremap s/ <Cmd>FuzzyMotion<CR>
'''
hook_source = '''
let g:fuzzy_motion_auto_jump = v:true
let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
'''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'lambdalisue/kensaku-search.vim'
depends = 'kensaku.vim'
on_map = { 'c' = '<Plug>(kensaku-search-replace)' }
hook_add = '''
cnoremap <CR> <Plug>(kensaku-search-replace)<CR>
'''

[[plugins]]
repo = 'kat0h/bufpreview.vim'
depends = ['denops.vim', 'open-browser.vim']
build = 'deno task prepare'
on_cmd = ['PreviewMarkdown', 'PreviewMarkdownToggle']
hook_source = '''
let g:bufpreview_server_port = '11223'
'''
