# Git plugins
[[plugins]] # vim-gitbranch
repo = 'itchyny/vim-gitbranch'

[[plugins]] # gitsigns.nvim
repo = 'lewis6991/gitsigns.nvim'
on_lua = 'gitsigns'
hooks_file = '$BASE_DIR/hooks/gitsigns.lua'

[[plugins]] # gina.vim
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = ['denops.vim', 'gina.vim']
on_cmd = ['Gin', 'GinBranch', 'GinCd', 'GinChaperon', 'GinDiff', 'GinLog', 'GinPatch', 'GinStatus']
hooks_file = '$BASE_DIR/hooks/gin.lua'
