# Git plugins
[[plugins]] # vim-gitbranch
repo = 'itchyny/vim-gitbranch'

[[plugins]] # gitsigns.nvim
repo = 'lewis6991/gitsigns.nvim'
on_source = 'nightfox.nvim'
hooks_file = '~/.config/nvim/hooks_files/gitsigns.lua'

[[plugins]] # gina.vim
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_add = '''
nnoremap gBB <Cmd>Gina blame<CR>
'''
hook_source = '''
call gina#custom#command#option('blame', '--opener', 'tabedit')
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_cmd = ['Gin', 'GinBranch', 'GinCd', 'GinChaperon', 'GinDiff', 'GinLog', 'GinPatch', 'GinStatus']
hooks_file = '~/.config/nvim/hooks_files/gin.vim'
