# Lazy load plugins
# Editor support plugins {{{
[[plugins]] # lightline.vim
repo = 'itchyny/lightline.vim'
on_event = ['WinNew', 'CursorHold', 'InsertEnter', 'CmdlineEnter']
depends = ['vim-gitbranch']
hooks_file = '$HOOKS_DIR/lightline.lua'

[[plugins]] # context_filetype.vim
repo = 'Shougo/context_filetype.vim'
lua_source = '''
vim.g['context_filetype#ignore_patterns'] = {
  toml = {
    [[^\s*#\s*]],
  }
}
'''

[[plugins]] # nvim-notify
repo = 'rcarriga/nvim-notify'
on_lua = 'notify'
lua_source = '''
require("notify").setup({
  stages = "slide",
  background_color = "NormalFloat",
})
vim.notify = require("notify")
'''

[[plugins]] # suda.vim
repo = 'lambdalisue/suda.vim'
on_cmd = ['SudaRead', 'SudaWrite']

[[plugins]] # vim-quickrun
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]] # vim-molder
repo = 'mattn/vim-molder'
hooks_file = '$HOOKS_DIR/molder.lua'

[[plugins]] # vim-molder-operations
repo = 'mattn/vim-molder-operations'
on_source = 'vim-molder'

[[plugins]] # helpful.vim
repo = 'tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'

[[plugins]] # deol.nvim
repo = 'Shougo/deol.nvim'
depends = ['ddc.vim']
on_cmd = 'Deol'
hooks_file = '$HOOKS_DIR/deol.lua'

[[plugins]] # open-browser.vim
repo = 'tyru/open-browser.vim'
on_map = { 'nx' = '<Plug>(openbrowser-smart-search)' }
lua_add = '''
-- open-browser.vim
vim.g.netrw_nogx = 1 -- disable netrw's gx mapping.
vim.keymap.set({"n", "x"}, [[gx]], [[<Plug>(openbrowser-smart-search)]], { noremap = false })
'''

[[plugins]] # vim-qfreplace
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

[[plugins]] # vim-qfedit
repo = 'itchyny/vim-qfedit'
on_event = 'QuickFixCmdPost'

[[plugins]] # ccc.nvim
repo = 'uga-rosa/ccc.nvim'
on_ft = ['css', 'html', 'conf']
on_cmd = ['CccPick', 'CccConvert', 'CccHighlighterToggle']
on_source = 'mason-lspconfig.nvim'
hooks_file = '$HOOKS_DIR/ccc.lua'

[[plugins]] # promise-async
repo = 'kevinhwang91/promise-async'
on_lua = ['async', 'promise']

[[plugins]] # nvim-ufo
repo = 'kevinhwang91/nvim-ufo'
depends = 'promise-async'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/ufo.lua'

# }}}

# Coding support plugins {{{
[[plugins]] # lexima.vim
repo = 'cohama/lexima.vim'
hooks_file = '$HOOKS_DIR/lexima.lua'

[[plugins]] # vim-eft
repo = 'hrsh7th/vim-eft'
on_map = { nxo = '<Plug>(eft-' }
hooks_file = '$HOOKS_DIR/eft.lua'

[[plugins]] # vim-sandwich
repo = 'machakann/vim-sandwich'
on_map = { nxo = '<Plug>(sandwich-' }
hooks_file = '$HOOKS_DIR/sandwich.lua'

[[plugins]] # dial.nvim
repo = 'monaqa/dial.nvim'
on_lua = ['dial.map', 'dial.augend', 'dial.config']
on_cmd = ['DialIncrement', 'DialDecrement']
hooks_file = '$HOOKS_DIR/dial.lua'
# }}}

# Filetype plugins {{{
[[plugins]] # plantuml-syntax
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]] # vim-maketable
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]] # previm
repo = 'previm/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
on_cmd = 'PrevimOpen'
hooks_file = '$HOOKS_DIR/previm/previm.lua'

[[plugins]] # tsnode-marker.nvim
repo = 'atusy/tsnode-marker.nvim'
on_ft = 'markdown'
hooks_file = '$HOOKS_DIR/tsnode_marker.lua'

# }}}
