# Lazy load plugins
# Colorscheme {{{
[[plugins]] # nightfox.nvim
repo = 'EdenEast/nightfox.nvim'
depends = ['nvim-treesitter']
on_event = 'VimEnter'
hooks_file = '$BASE_DIR/hooks/nightfox.lua'

# }}}

# Editor support plugins {{{
[[plugins]] # lightline.vim
repo = 'itchyny/lightline.vim'
on_event = ['WinNew', 'CursorHold', 'InsertEnter', 'CmdlineEnter']
depends = ['vim-gitbranch']
hooks_file = '$BASE_DIR/hooks/lightline.lua'

[[plugins]] # context_filetype.vim
repo = 'Shougo/context_filetype.vim'
lua_source = '''
vim.g['context_filetype#ignore_patterns'] = {
  toml = {
    [[^\s*#\s*]],
  }
}
'''

[[plugins]] # nvim-notify
repo = 'rcarriga/nvim-notify'
on_source = 'nightfox.nvim'
lua_source = '''
require("notify").setup({
  stages = "slide",
  background_color = "NormalFloat",
})
vim.notify = require("notify")
'''

[[plugins]] # suda.vim
repo = 'lambdalisue/suda.vim'
on_cmd = ['SudaRead', 'SudaWrite']

[[plugins]] # vim-quickrun
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]] # vim-molder
repo = 'mattn/vim-molder'
hooks_file = '$BASE_DIR/hooks/molder.lua'

[[plugins]] # vim-molder-operations
repo = 'mattn/vim-molder-operations'
on_source = 'vim-molder'

[[plugins]] # helpful.vim
repo = 'tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'

[[plugins]] # bracey.vim
repo = 'turbio/bracey.vim'
on_cmd = 'Bracey'

[[plugins]] # deol.nvim
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hooks_file = '$BASE_DIR/hooks/deol.lua'

[[plugins]] # open-browser.vim
repo = 'tyru/open-browser.vim'
on_map = { 'nx' = '<Plug>(openbrowser-smart-search)' }
lua_add = '''
-- open-browser.vim
vim.g.netrw_nogx = 1 -- disable netrw's gx mapping.
vim.keymap.set({"n", "x"}, [[gx]], [[<Plug>(openbrowser-smart-search)]], { noremap = false })
'''

# }}}

# Coding support plugins {{{
[[plugins]] # lexima.vim
repo = 'cohama/lexima.vim'
hooks_file = '$BASE_DIR/hooks/lexima.lua'

[[plugins]] # vim-eft
repo = 'hrsh7th/vim-eft'
on_map = { nxo = '<Plug>(eft-' }
hooks_file = '$BASE_DIR/hooks/eft.lua'

[[plugins]] # vim-cursorword
repo = 'itchyny/vim-cursorword'
on_source = 'nightfox.nvim'

[[plugins]] # vim-sandwich
repo = 'machakann/vim-sandwich'
on_map = { nxo = '<Plug>(sandwich-' }
hooks_file = '$BASE_DIR/hooks/sandwich.lua'

# }}}

# Filetype plugins {{{
[[plugins]] # emmet-vim
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'php']
hooks_file = '$BASE_DIR/hooks/emmet.lua'

[[plugins]] # plantuml-syntax
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]] # vim-maketable
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]] # previm
repo = 'previm/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
on_cmd = 'PrevimOpen'
hooks_file = '$BASE_DIR/hooks/previm.lua'

[[plugins]]
repo = 'atusy/tsnode-marker.nvim'
on_ft = 'markdown'
hooks_file = '$BASE_DIR/hooks/tsnode_marker.lua'

# }}}
