# LSP plugins
## Builtin lsp core plugins {{{
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = [ 'neodev.nvim' ]

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_source = '''
local mason = require('mason')
mason.setup({
  ui = {
    border = 'single',
    icons = {
      package_installed   = '',
      package_pending     = '',
      package_uninstalled = '✗ ',
    },
  }
})
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_ft = [ 'lua', 'php', 'python', 'toml', 'markdown' ]
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
lua_source = '''
local mason_lspconfig = require('mason-lspconfig')
local lspconfig = require("lspconfig")
local saga = require('lspsaga')
local keymap = vim.keymap.set
local lsp = vim.lsp -- nvim lsp api.
local diag = vim.diagnostic -- nvim diagnostic api.

mason_lspconfig.setup({
  ensure_installed = {
    'sumneko_lua',
    'intelephense',
    'pyright',
  },
  automatic_installation = true,
})

saga.init_lsp_saga({
  border_style = 'single',
  finder_action_keys = {
    open = 'o',
    vsplit = 'v',
    split = 's',
    tabe = 't',
    quit = { 'q', '<ESC>' },
  },
  rename_action_quit = '<ESC>',
  rename_in_select = false,
  show_outline = {
    win_with = 'defx',
    win_width = 40,
  }
})

mason_lspconfig.setup_handlers({ function(server_name)
  local lsp_options = {}

  lsp_options.on_attach = function(client, bufnr)
    local keymap_options = {
      noremap = true,
      --silent = true,
      buffer = bufnr,
    }

    print(client.name)

    -- About <lsp> prefix ~/dotfiles/config/nvim/rc/keybinds.vim:89
    keymap('n', '<lsp>k', '<Cmd>Lspsaga hover_doc<CR>', keymap_options)
    keymap('n', '<lsp>K', '<Cmd>Lspsaga lsp_finder<CR>', keymap_options)
    keymap('n', '<lsp>r', '<Cmd>Lspsaga rename<CR>', keymap_options)
    keymap('n', '<lsp>o', '<Cmd>LSoutlineToggle<CR>', keymap_options)
    keymap({ 'n', 'x' }, '<lsp>c', '<Cmd>Lspsaga code_action<CR>', keymap_options)
    keymap('n', '<lsp>h', lsp.buf.signature_help, keymap_options)
    keymap('n', '<lsp>f', lsp.buf.format, keymap_options)
    keymap('n', '<lsp>i', lsp.buf.implementation, keymap_options)
    keymap('n', '<lsp>d', '<Cmd>Lspsaga peek_definition<CR>', keymap_options)
    keymap('n', '<lsp>D', lsp.buf.declaration, keymap_options)
    keymap('n', '<lsp>E', '<Cmd>Lspsaga show_cursor_diagnostics<CR>', keymap_options)
    keymap('n', '<lsp>e', '<Cmd>Lspsaga show_line_diagnostics<CR>', keymap_options)
    keymap('n', '<lsp>q', diag.setloclist, keymap_options)
    keymap('n', '[d', '<Cmd>Lspsaga diagnostic_jump_prev<CR>', keymap_options)
    keymap('n', ']d', '<Cmd>Lspsaga diagnostic_jump_next<CR>', keymap_options)
  end

  local capabilities = lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  if server_name == 'sumneko_lua' then
    lsp_options.capabilities = capabilities
  end

  lspconfig[server_name].setup(lsp_options)
end })
'''

# }}}

## LSP extends plugins {{{
[[plugins]]
repo = 'glepnir/lspsaga.nvim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'nvim-lspconfig'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'nvim-lspconfig'
hook_source = '''
call signature_help#enable()
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_source = 'nvim-lspconfig'
lua_source = '''
require('fidget').setup({
  text = {
    spinner = 'dots',
  },
  window = {
    border = 'single',
    relative = 'editor',
  },
})
'''

# }}}

## null-ls plugins {{{

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = [ 'nvim-lspconfig', 'plenary.nvim' ]
lua_source = '''
local null_ls = require('null-ls')

local code_actions = null_ls.builtins.code_actions
local completion = null_ls.builtins.completion
local diagnostics = null_ls.builtins.diagnostics
local formatting = null_ls.builtins.formatting
--local hover = null_ls.builtins.hover

local sources = {
  code_actions.gitsigns,
  completion.vsnip,
  formatting.stylua,
  diagnostics.selene,
  diagnostics.textlint.with({
    condition = function()
      return vim.fn.executable('textlint') > 0
    end,
    filetypes = { 'markdown' },
    prefer_local = "node_modules/.bin",
  }),
}

null_ls.setup({
  border = 'single',
  diagnostics_format = '[#{c}] #{m} (#{s})',
  sources = sources,
})
'''

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
depends = [ 'mason.nvim', 'null-ls.nvim' ]
on_ft = [ 'lua', 'markdown' ]
lua_source = '''
require('mason-null-ls').setup({
  ensure_installed = nil,
  automatic_installation = {
    exclude = {
      'textlint',
    },
  },
  automatic_setup = false,
})
'''

# }}}

## Language server support plugins {{{
[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'

[[plugins]]
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''

# }}}
