# LSP plugins
## Builtin lsp core plugins {{{
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['neodev.nvim']

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_source = '''
require('plugins.mason.core')
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_ft = ['lua', 'php', 'python', 'toml', 'markdown']
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
lua_source = '''
require("plugins.mason.lspconfig")
'''

# }}}

## LSP extends plugins {{{
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
lua_source = '''
require("plugins.lspsaga")
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'nvim-lspconfig'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'nvim-lspconfig'
hook_source = '''
call signature_help#enable()
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_source = 'nvim-lspconfig'
lua_source = '''
require('plugins.fidget')
'''

# }}}

## null-ls plugins {{{

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['nvim-lspconfig', 'plenary.nvim']
lua_source = '''
require("plugins.null_ls")
'''

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
depends = ['mason.nvim', 'null-ls.nvim']
on_ft = ['lua', 'markdown']
lua_source = '''
require('plugins.mason.null_ls')
'''

# }}}

## Language server support plugins {{{
[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'

[[plugins]]
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''

# }}}
