# LSP plugins
## Builtin lsp core plugins {{{
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = 'neodev.nvim'

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_source = '''
require('plugins.lsp.mason')
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
on_ft = ['lua', 'php', 'python', 'toml', 'markdown', 'vim']
hook_add = '''
" LSP keybinds {{{
nnoremap <lsp>k <Cmd>Lspsaga hover_doc<CR>
nnoremap <lsp>K <Cmd>Lspsaga lsp_finder<CR>
nnoremap <lsp>r <Cmd>Lspsaga rename<CR>
nnoremap <lsp>o <Cmd>LSoutlineToggle<CR>
nnoremap <lsp>c <Cmd>Lspsaga code_action<CR>
nnoremap <lsp>h <Cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <lsp>f <Cmd>lua vim.lsp.buf.format()<CR>
nnoremap <lsp>i <Cmd>lua vim.lsp.buf.implementation<CR>
nnoremap <lsp>d <Cmd>Lspsaga peek_definition<CR>
nnoremap <lsp>D <Cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <lsp>e <Cmd>Lspsaga show_line_diagnostics<CR>
nnoremap <lsp>E <Cmd>Lspsaga show_cursor_diagnostics<CR>
nnoremap <lsp>q <Cmd>lua vim.diagnostic.setloclist()<CR>
nnoremap [d <Cmd>Lspsaga diagnostic_jump_prev<CR>
nnoremap ]d <Cmd>Lspsaga diagnostic_jump_next<CR>
" }}}
'''
lua_source = '''
require("plugins.lsp.config")
'''

# }}}

## LSP extends plugins {{{
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
lua_source = '''
require("plugins.lspsaga")
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'nvim-lspconfig'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'nvim-lspconfig'
hook_source = '''
call signature_help#enable()
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_source = 'nvim-lspconfig'
lua_source = '''
require('plugins.fidget')
'''

# }}}

## null-ls plugins {{{

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
lua_source = '''
require("plugins.lsp.null_ls")
'''

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
depends = 'null-ls.nvim'
on_source = 'mason-lspconfig.nvim'
lua_source = '''
require('plugins.lsp.mason_null_ls')
'''

# }}}

## Language server support plugins {{{
[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'

[[plugins]]
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''

# }}}
