# LSP plugins
# Core plugins {{{
[[plugins]] # nvim-lspconfig
repo = 'neovim/nvim-lspconfig'
depends = 'neodev.nvim'

[[plugins]] # mason.nvim
repo = 'williamboman/mason.nvim'
hooks_file = '~/.config/nvim/hooks/mason.lua'

[[plugins]] # mason-lspconfig.nvim
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
on_source = 'ddc.vim'
hooks_file = '~/.config/nvim/hooks/mason_lspconfig.lua'

# }}}

# Support plugins {{{
[[plugins]] # lspsaga.nvim
repo = 'glepnir/lspsaga.nvim'
hooks_file = '~/.config/nvim/hooks/lspsaga.lua'

[[plugins]] # denops-popup-preview.vim
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]] # denops-signature_help
repo = 'matsui54/denops-signature_help'
on_event = 'LspAttach'
hook_source = '''
call signature_help#enable()
'''

[[plugins]] # fidget.nvim
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
hooks_file = '~/.config/nvim/hooks/fidget.lua'

[[plugins]] # neodev.nvim
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''
# }}}

# null_ls {{{
[[plugins]] # plenary.nvim(null-ls depends of this plugin) 
repo = 'nvim-lua/plenary.nvim'

[[plugins]] # null-ls.nvim
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
hooks_file = '~/.config/nvim/hooks/null_ls.lua'

[[plugins]] # mason-null-ls.nvim
repo = 'jay-babu/mason-null-ls.nvim'
depends = 'null-ls.nvim'
on_source = 'mason-lspconfig.nvim'
hooks_file = '~/.config/nvim/hooks/mason_null_ls.lua'

# }}}
