# LSP plugins
## Builtin lsp core plugins {{{
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = [ 'neodev.nvim' ]

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_source = '''
local mason = require('mason')
mason.setup({
  ui = {
    border = 'single',
    icons = {
      package_installed   = '',
      package_pending     = '',
      package_uninstalled = '✗ ',
    },
  }
})
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_ft = [ 'toml', 'lua', 'php', 'python' ]
depends = ['nvim-lspconfig', 'mason.nvim']
lua_source = '''
local mason_lspconfig = require('mason-lspconfig')
local lspconfig = require("lspconfig")
local lsp = vim.lsp -- nvim lsp api.
local diag = vim.diagnostic -- nvim diagnostic api.

mason_lspconfig.setup({
  ensure_installed = {
    'sumneko_lua',
    'intelephense',
    'pyright',
  },
  automatic_installation = true,
})

mason_lspconfig.setup_handlers({ function(server_name)
  local lsp_options = {}

  lsp_options.on_attach = function(client, bufnr)
    local keymap_options = { noremap = true, buffer = bufnr }
    -- About <lsp> prefix ~/dotfiles/config/nvim/rc/keybinds.vim:89
    vim.keymap.set('n', '<lsp>k', lsp.buf.hover, keymap_options)
    vim.keymap.set('n', '<lsp>h', lsp.buf.signature_help, keymap_options)
    vim.keymap.set('n', '<lsp>i', lsp.buf.implementation, keymap_options)
    vim.keymap.set('n', '<lsp>d', lsp.buf.definition, keymap_options)
    vim.keymap.set('n', '<lsp>D', lsp.buf.declaration, keymap_options)
    vim.keymap.set('n', '<lsp>e', diag.open_float, keymap_options)
    vim.keymap.set('n', '<lsp>q', diag.setloclist, keymap_options)
    vim.keymap.set('n', '[d', diag.goto_prev, keymap_options)
    vim.keymap.set('n', ']d', diag.goto_next, keymap_options)
  end

  lsp.handlers['textDocument/hover'] = lsp.with(
    lsp.handlers.hover, {
      border = 'single',
    })

  lsp.handlers['textDocument/signatureHelp'] = lsp.with(
    lsp.handlers.signature_help, {
      border = 'single',
    })

  lsp.handlers['textDocument/publishDiagnostics'] = lsp.with(
    lsp.diagnostic.on_publish_diagnostics, {
      virtual_text = false,
    }
  )

  local capabilities = lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  if server_name == 'sumneko_lua' then
    lsp_options.capabilities = capabilities
  end

  lspconfig[server_name].setup(lsp_options)
end })
'''

# }}}

# Language server support plugins {{{
[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'

[[plugins]]
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''

# }}}

# LSP extends plugins {{{
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc-source-nvim-lsp'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc-source-nvim-lsp'
hook_source = '''
call signature_help#enable()
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_source = 'ddc-source-nvim-lsp'
lua_source = '''
require('fidget').setup({
  text = {
    spinner = 'dots',
  },
  window = {
    relative = 'editor',
  },
})
'''

# }}}
