# LSP plugins
[[plugins]] # nvim-lspconfig
repo = 'neovim/nvim-lspconfig'
depends = 'neodev.nvim'

[[plugins]] # mason.nvim
repo = 'williamboman/mason.nvim'
lua_source = '''
-- <% partial_path: ./partial/mason.lua
require("mason").setup({
  ui = {
    border = "single",
    icons = {
      package_installed = "",
      package_pending = "",
      package_uninstalled = "✗ ",
    },
  },
})
-- %>
'''

[[plugins]] # mason-lspconfig.nvim
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
on_ft = ['lua', 'php', 'python', 'toml', 'markdown', 'vim']
hook_add = '''
" LSP keybinds
nnoremap <lsp>k <Cmd>Lspsaga hover_doc<CR>
nnoremap <lsp>K <Cmd>Lspsaga lsp_finder<CR>
nnoremap <lsp>r <Cmd>Lspsaga rename<CR>
nnoremap <lsp>o <Cmd>Lspsaga outline<CR>
nnoremap <lsp>c <Cmd>Lspsaga code_action<CR>
nnoremap <lsp>h <Cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <lsp>f <Cmd>lua vim.lsp.buf.format()<CR>
nnoremap <lsp>i <Cmd>lua vim.lsp.buf.implementation<CR>
nnoremap <lsp>d <Cmd>Lspsaga peek_definition<CR>
nnoremap <lsp>D <Cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <lsp>e <Cmd>Lspsaga show_line_diagnostics<CR>
nnoremap <lsp>E <Cmd>Lspsaga show_cursor_diagnostics<CR>
nnoremap <lsp>q <Cmd>Lspsaga show_buf_diagnostics<CR>
nnoremap [d <Cmd>Lspsaga diagnostic_jump_prev<CR>
nnoremap ]d <Cmd>Lspsaga diagnostic_jump_next<CR>
'''
lua_source = '''
require("plugins.lsp.config")
'''

[[plugins]] # lspsaga.nvim
repo = 'glepnir/lspsaga.nvim'
lua_source = '''
require("plugins.lsp.lspsaga")
'''

[[plugins]] # denops-popup-preview.vim
repo = 'matsui54/denops-popup-preview.vim'
on_event = 'LspAttach'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]] # denops-signature_help
repo = 'matsui54/denops-signature_help'
on_event = 'LspAttach'
hook_source = '''
call signature_help#enable()
'''

[[plugins]] # fidget.nvim
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
lua_source = '''
require('plugins.lsp.fidget')
'''

[[plugins]] # plenary.nvim(null-ls depends of this plugin) 
repo = 'nvim-lua/plenary.nvim'

[[plugins]] # null-ls.nvim
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
lua_source = '''
require("plugins.lsp.null_ls")
'''

[[plugins]] # mason-null-ls.nvim
repo = 'jay-babu/mason-null-ls.nvim'
depends = 'null-ls.nvim'
on_source = 'mason-lspconfig.nvim'
lua_source = '''
require('plugins.lsp.mason_null_ls')
'''

[[plugins]] # neodev.nvim
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''
