# LSP plugins
# Core plugins {{{
[[plugins]] # nvim-lspconfig
repo = 'neovim/nvim-lspconfig'

[[plugins]] # mason.nvim
repo = 'williamboman/mason.nvim'
hook_post_update = 'MasonUpdate'
hooks_file = '$HOOKS_DIR/mason.lua'

[[plugins]] # mason-lspconfig.nvim
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim', 'ddc-source-lsp', 'nvim-navic']
on_source = 'ddc.vim'
on_ft = ['lua', 'pyhton', 'php', 'markdown', 'typescript']
lua_source = '''
-- $BASE_DIR/lua/user/lsp
require("user.lsp")
'''

# }}}

# Support plugins {{{
[[plugins]] # denops-popup-preview.vim
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
lua_source = '''
vim.fn['popup_preview#enable']()
'''

[[plugins]] # denops-signature_help
repo = 'matsui54/denops-signature_help'
on_event = 'LspAttach'
lua_source = '''
vim.fn['signature_help#enable']()
'''

[[plugins]] # fidget.nvim
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
hooks_file = '$HOOKS_DIR/fidget.lua'

[[plugins]]
repo = 'creativenull/efmls-configs-nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'SmiteshP/nvim-navic'
hooks_file = "$HOOKS_DIR/navic.lua"
# }}}
