# LSP plugins
# Core plugins {{{
[[plugins]] # nvim-lspconfig
repo = 'neovim/nvim-lspconfig'
depends = 'neodev.nvim'

[[plugins]] # mason.nvim
repo = 'williamboman/mason.nvim'
hooks_file = '~/.config/nvim/hooks/mason.lua'

[[plugins]] # mason-lspconfig.nvim
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim', 'lspsaga.nvim']
on_source = 'ddc.vim'
hooks_file = '~/.config/nvim/hooks/mason_lspconfig.lua'
hook_add = '''
" LSP keybinds
nnoremap <Plug>(lsp)k <Cmd>Lspsaga hover_doc<CR>
nnoremap <Plug>(lsp)K <Cmd>Lspsaga lsp_finder<CR>
nnoremap <Plug>(lsp)r <Cmd>Lspsaga rename<CR>
nnoremap <Plug>(lsp)o <Cmd>Lspsaga outline<CR>
nnoremap <Plug>(lsp)c <Cmd>Lspsaga code_action<CR>
nnoremap <Plug>(lsp)h <Cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <Plug>(lsp)f <Cmd>lua vim.lsp.buf.format()<CR>
nnoremap <Plug>(lsp)i <Cmd>lua vim.lsp.buf.implementation<CR>
nnoremap <Plug>(lsp)d <Cmd>Lspsaga peek_definition<CR>
nnoremap <Plug>(lsp)D <Cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <Plug>(lsp)e <Cmd>Lspsaga show_line_diagnostics<CR>
nnoremap <Plug>(lsp)E <Cmd>Lspsaga show_cursor_diagnostics<CR>
nnoremap <Plug>(lsp)q <Cmd>Lspsaga show_buf_diagnostics<CR>
nnoremap [d <Cmd>Lspsaga diagnostic_jump_prev<CR>
nnoremap ]d <Cmd>Lspsaga diagnostic_jump_next<CR>
'''

# }}}

# Support plugins {{{
[[plugins]] # lspsaga.nvim
repo = 'glepnir/lspsaga.nvim'
hooks_file = '~/.config/nvim/hooks/lspsaga.lua'

[[plugins]] # denops-popup-preview.vim
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]] # denops-signature_help
repo = 'matsui54/denops-signature_help'
on_event = 'LspAttach'
hook_source = '''
call signature_help#enable()
'''

[[plugins]] # fidget.nvim
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
hooks_file = '~/.config/nvim/hooks/fidget.lua'

[[plugins]] # neodev.nvim
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''
# }}}

# null_ls {{{
[[plugins]] # plenary.nvim(null-ls depends of this plugin) 
repo = 'nvim-lua/plenary.nvim'

[[plugins]] # null-ls.nvim
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
hooks_file = '~/.config/nvim/hooks/null_ls.lua'

[[plugins]] # mason-null-ls.nvim
repo = 'jay-babu/mason-null-ls.nvim'
depends = 'null-ls.nvim'
on_source = 'mason-lspconfig.nvim'
hooks_file = '~/.config/nvim/hooks/mason_null_ls.lua'

# }}}
