# LSP plugins
# Core plugins {{{
[[plugins]] # nvim-lspconfig
repo = 'neovim/nvim-lspconfig'
depends = 'neodev.nvim'

[[plugins]] # mason.nvim
repo = 'williamboman/mason.nvim'
hook_post_update = 'MasonUpdate'
hooks_file = '$HOOKS_DIR/mason.lua'

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'

[[plugins]] # mason-lspconfig.nvim
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim']
on_source = 'ddc.vim'
on_ft = ['lua', 'pyhton', 'php', 'markdown', 'typescript']
hooks_file = '$HOOKS_DIR/lspconfig.lua'

# }}}

# Support plugins {{{
[[plugins]] # denops-popup-preview.vim
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
lua_source = '''
vim.fn['popup_preview#enable']()
'''

[[plugins]] # denops-signature_help
repo = 'matsui54/denops-signature_help'
on_event = 'LspAttach'
lua_source = '''
vim.fn['signature_help#enable']()
'''

[[plugins]] # fidget.nvim
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
rev = 'legacy'
hooks_file = '$HOOKS_DIR/fidget.lua'

[[plugins]] # neodev.nvim
repo = 'folke/neodev.nvim'
lua_source = '''
require("neodev").setup({})
'''

[[plugins]]
repo = 'creativenull/efmls-configs-nvim'
on_source = 'nvim-lspconfig'
# }}}
