[[plugins]] # nvim-treesitter
repo = 'nvim-treesitter/nvim-treesitter'
rev = 'v0.9.2'
on_event = 'BufRead'
hooks_file = '$HOOKS_DIR/treesitter.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/ts_textobjects.lua'

[[plugins]] # indent-blankline.nvim
repo = 'lukas-reineke/indent-blankline.nvim'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/indent_blankline.lua'

[[plugins]] # matchparen.nvim
repo = 'monkoose/matchparen.nvim'
on_source = 'nvim-treesitter'
lua_source = '''
require('matchparen').setup()
'''

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'

[[plugins]] # Comment.nvim
repo = 'numToStr/Comment.nvim'
depends = 'nvim-ts-context-commentstring'
on_map = { nox = '<Plug>(comment_toggle_' }
on_event = ['CursorHold', 'InsertEnter']
hooks_file = '$HOOKS_DIR/comment_nvim.lua'

[[plugins]] #nvim-yati
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/illuminate.lua'
