[[plugins]] # nvim-treesitter
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hooks_file = '$HOOKS_DIR/treesitter.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/ts_textobjects.lua'

[[plugins]] # indent-blankline.nvim
repo = 'lukas-reineke/indent-blankline.nvim'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/indent_blankline.lua'

[[plugins]] # matchparen.nvim
repo = 'monkoose/matchparen.nvim'
on_source = 'nvim-treesitter'
lua_source = '''
require('matchparen').setup()
'''

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'

[[plugins]] #nvim-yati
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/illuminate.lua'

[[plugins]]
repo = 'https://gitlab.com/HiPhish/rainbow-delimiters.nvim'
on_source = 'nvim-treesitter'
hooks_file = '$HOOKS_DIR/rainbow_delimiters.lua'

