[[plugins]] # Dark power plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # Color scheme for editor
repo = 'cocopon/iceberg.vim'

[[plugins]] # Modern and light status line.
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.vim/lightline.rc.vim
'''

[[plugins]] # Preview of replacement results
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'
