[[plugins]] # Dark power plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # Color scheme for editor
repo = 'cocopon/iceberg.vim'

[[plugins]] # Modern and light status line.
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [figitive] <Nop>
    nnoremap <Leader>g [figitive]
    nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
