---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.216.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: rossmacarthur/sheldon@0.7.4
- name: jdx/mise@v2024.8.12
- name: sharkdp/bat@v0.24.0
- name: cli/cli@v2.55.0
- name: jqlang/jq@jq-1.7.1
- name: BurntSushi/ripgrep@14.1.0
- name: x-motemen/ghq@v1.6.2
- name: oven-sh/bun@bun-v1.1.26
- name: dandavison/delta@0.18.0
- name: denoland/deno@v1.46.1
- name: sharkdp/fd@v10.2.0
- name: junegunn/fzf@v0.54.3
- name: eza-community/eza@v0.19.0
- name: golang/go@go1.23.0
- name: xo/usql@v0.19.3
- name: charmbracelet/glow@v1.5.1
- name: volta-cli/volta@v2.0.1
- name: aws/aws-cli@2.17.32
