---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.177.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: rossmacarthur/sheldon@0.7.4
- name: jdx/mise@v2024.5.5
- name: sharkdp/bat@v0.24.0
- name: cli/cli@v2.49.2
