[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = 'InsertEnter'
hook_source = '''
    source ~/dotfiles/.vim/plugins/ddc.vim
'''
hook_add = '''
    source ~/dotfiles/.vim/plugins/cmddc.vim
'''

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source ='ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-rg'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'toml', 'markdown']
depends = 'ddc.vim'
hook_source = '''
    call ddc#custom#patch_filetype(
        \ ['vim'], 'sources', 
        \ ['necovim', 'around', 'neosnippet', 'file', 'rg'],
        \ )
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['impatient.nvim', 'ddc.vim']
on_ft = ['python']
hook_source = '''
lua << EOF
require('lspconfig').pyright.setup{}
EOF
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'nvim-lspconfig'

#[[plugins]]
#repo = 'matsui54/ddc-nvim-lsp-doc'
#on_source = 'ddc-nvim-lsp'
#hook_source = '''
#    call ddc_nvim_lsp_doc#enable()
#'''

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertEnter'
hook_source = '''
    source ~/dotfiles/.vim/plugins/neosnippet.vim
'''
on_ft = 'snippet'
depends = 'neosnippet-snippets'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/skkeleton.vim
'''
