## ddu core plugins {{{
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_func = 'ddu#start()'
hook_add = '''
nnoremap [ff] <Nop>
nmap <Space>d [ff]
nnoremap [ff]a <Cmd>call ddu#start({'name': 'current-ff'})<CR>
nnoremap [ff]d <Cmd>call ddu#start({'name': 'dotfiles-ff'})<CR>
nnoremap [ff]h <Cmd>call ddu#start({'name': 'help-ff'})<CR>
nnoremap [ff]b <Cmd>call ddu#start({'name': 'buffer-ff'})<CR>
nnoremap [ff]P <Cmd>call ddu#start({'name': 'plugin-list-ff'})<CR>
nnoremap [ff]p <Cmd>call ddu#start({'name': 'project-list-ff'})<CR>
nnoremap [ff]~ <Cmd>call ddu#start({'name': 'home-ff'})<CR>
nnoremap [ff]r <Cmd>call ddu#start({'name': 'register-ff'})<CR>
nnoremap [ff]s <Cmd>call ddu#start({
  \ 'name': 'search-ff',
  \ 'sources': [{
    \ 'name': 'rg',
    \ 'params': {'input': input('Pattern: ')},
    \ }],
  \ })<CR>

nnoremap [filer] <Nop>
nmap <Space>f [filer]
nnoremap [filer]a <Cmd>call ddu#start({
  \ 'name': 'current-filer',
  \ 'sourceOptions': {
    \ 'file': {'path': expand('%:p:h')},
    \ },
  \ })<CR>
'''
hook_source = '''
source ~/dotfiles/.vim/plugins/ddu.vim
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

## }}}

## ddu-kind {{{

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'

## }}}

## ddu-source {{{

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

## }}}

## ddu-filter {{{

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'

## }}}

## ddu-column {{{

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# }}}
