[[plugins]] # Dark power plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # Color scheme for editor
repo = 'cocopon/iceberg.vim'

[[plugins]] # Modern and light status line.
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/dotfiles/.vim/plugins/lightline.vim
'''

[[plugins]] # Preview of replacement results
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [fugitive] <Nop>
    nmap <Space>g [fugitive]
    nnoremap [fugitive]s <cmd>Git<CR>
    nnoremap [fugitive]a <cmd>Gwrite<CR>
    nnoremap [fugitive]d <cmd>Gdiff<CR>
    nnoremap [fugitive]b <cmd>Gblame<CR>
    nnoremap [fugitive]c <cmd>Git commit -v<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
    nmap <F8> :TagbarToggle<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
