[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'php']
hook_add = '''
  let g:user_emmet_install_global = 0
  autocmd FileType html,css,php EmmetInstall
  let g:user_emmet_settings = {
    \ 'variables': {
      \ 'lang': "ja"
      \ },
    \ 'html': {
      \ 'snippets': {
        \ 'html:5': "<!DOCTYPE html>\n"
        \ ."<html lang=\"${lang}\">\n"
        \ ."\t<head>\n"
        \ ."\t\t<meta charset=\"${charset}\">\n"
        \ ."\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        \ ."\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
        \ ."\t\t<title></title>\n"
        \ ."\t\t<link rel=\"stylesheet\" href=\"css/style.css\">\n"
        \ ."\t</head>\n"
        \ ."\t<body>\n\t${child}|\n\t</body>\n"
        \ ."</html>",
        \ 'lrl:s': "{{ | }}",
        \ 'lrl:e': "{!! | !!}",
        \ }
      \ },
      \ 'php': {
        \ 'snippets': {
          \ 'php:s': "<?php | ?>",
          \ 'php:e': "<?= | ?>",
          \ 'lrl:s': "{{ | }}",
          \ 'lrl:e': "{!! | !!}",
          \ }
        \ }
    \ }
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = '''
  augroup json_autocmd
    autocmd!
    autocmd FileType json set autoindent
    autocmd FileType json set formatoptions=tcq2l
    autocmd FileType json set textwidth=78 shiftwidth=2
    autocmd FileType json set softtabstop=2 tabstop=8
    autocmd FileType json set expandtab
    autocmd FileType json set foldmethod=syntax
  augroup END
'''

# Markdown plugins {{{

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
on_cmd = 'PrevimOpen'
hook_add = '''
  nnoremap [previm] <Nop>
  nmap <Space>p [previm]
  nnoremap [previm]o <Cmd>PrevimOpen<CR>
  nnoremap [previm]r <Cmd>call previm#refresh()<CR>
'''
hook_source = '''
  let g:previm_enable_realtime = 1
  let g:previm_disable_default_css = 1
  let g:previm_custom_css_path = expand('~/dotfiles/tmp/previm_markdown.css')
  let g:previm_plantuml_imageprefix = 'http://localhost:58080/png/'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  " open-browser.vim
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''
# }}}
