[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
    let g:user_emmet_install_global = 0
    autocmd FileType html,css EmmetInstall
    let g:user_emmet_settings = {
        \ 'variables': {
            \ 'lang': "ja"
            \ },
        \ 'html': {
            \ 'snippets': {
                \ 'html:5': "<!DOCTYPE html>\n"
                \ ."<html lang=\"${lang}\">\n"
                \ ."<head>\n"
                \ ."\t<meta charset=\"${charset}\">\n"
                \ ."\t<link rel=\"stylesheet\" href=\"css/style.css\">\n"
                \ ."</head>\n"
                \ ."<body>\n\t${child}|\n</body>\n"
                \ ."</html>",
                \ }
            \ }
        \ }
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = '''
    augroup json_autocmd
        autocmd!
        autocmd FileType json set autoindent
        autocmd FileType json set formatoptions=tcq2l
        autocmd FileType json set textwidth=78 shiftwidth=2
        autocmd FileType json set softtabstop=2 tabstop=8
        autocmd FileType json set expandtab
        autocmd FileType json set foldmethod=syntax
    augroup END
'''
