[[plugins]] # Japanese localization of help
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['h', 'help']

[[plugins]] # Translate, Japanese to English
repo = 'skanehira/translate.vim'
on_cmd = 'Translate'
hook_source = '''
    " Pop up the translated content
    let g:translate_popup_window = 1
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"

    " <S-TAB>: completion back.
    inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)

    " SuperTab like snippets behavior.
    imap <expr><TAB> pumvisible() ? 
    \ "\<C-n>" : neosnippet#jumpable() ? 
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

    if has('conceal')
        set conceallevel=2 concealcursor=niv
    endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
    source ~/dotfiles/.vim/plugins/denite.vim
'''
hook_add = '''
    nnoremap [denite] <Nop>
    nmap <Space>d [denite]
    nnoremap [denite]a <cmd>Denite file buffer file:new<CR>
    nnoremap [denite]b <cmd>Denite buffer<CR>
    nnoremap [denite]h <cmd>Denite help -start-filter<CR>
    nnoremap [denite]r <cmd>Denite register<CR>
    nnoremap [denite]g <cmd>Denite grep<CR>
    nnoremap [denite]m <cmd>Denite menu<CR>
    nnoremap [denite]dm <cmd>Denite menu:Denite_cmd<CR>
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    nnoremap [defx] <Nop>
    nmap <Space>f [defx]
    nnoremap [defx]a <cmd>Defx -search=`expand('%:p')` `expand('%:p:h')`<CR>
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/defx.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_ft = 'defx'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
    nnoremap [term] <Nop>
    nmap <Space>t [term]
    nnoremap [term]d <cmd>Deol -split=floating<CR>

    " Exit deol buffer with <ESC>
    tnoremap <ESC> <cmd>quit<CR>
'''
