[[plugins]] # Japanese localization of help
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['h', 'help']

[[plugins]]
repo = 'yasunori-kirin0418/lightline-skk'
on_source = 'skkeleton'

[[plugins]] # Preview of replacement results
repo = 'markonm/traces.vim'
on_event= 'CmdlineEnter'

[[plugins]] # Translate, Japanese to English
repo = 'skanehira/translate.vim'
on_cmd = 'Translate'
hook_source = '''
    " Pop up the translated content
    let g:translate_popup_window = 1
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'maintained',
    highlight = {
        enable = true,
        disable = { 'vim' },
    },
    indent = {
        enable = true,
    },
}
EOF
'''

#[[plugins]]
#repo = 'skanehira/denops-translate.vim'
#on_cmd = 'Translate'

[[plugins]]
repo = 'lambdalisue/suda.vim'
on_cmd = ['SudaRead', 'SudaWrite']

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
    nmap <F8> :TagbarToggle<CR>
'''

# [[plugins]]
# repo = 'wsdjeg/dein-ui.vim'
# on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
    source ~/dotfiles/.vim/plugins/denite.vim
'''
hook_add = '''
    nnoremap [denite] <Nop>
    nmap <Space>d [denite]
    nnoremap [denite]a <cmd>Denite file buffer file:new<CR>
    nnoremap [denite]b <cmd>Denite buffer<CR>
    nnoremap [denite]h <cmd>Denite help -start-filter<CR>
    nnoremap [denite]r <cmd>Denite register<CR>
    nnoremap [denite]g <cmd>Denite grep<CR>
    nnoremap [denite]m <cmd>Denite menu<CR>
    nnoremap [denite]dm <cmd>Denite menu:Denite_cmd<CR>
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
    nnoremap [defx] <Nop>
    nmap <Space>f [defx]
    nnoremap [defx]a <cmd>Defx -search=`expand('%:p')` `expand('%:p:h')`<CR>
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/defx.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_ft = 'defx'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
    nnoremap [term] <Nop>
    nmap <Space>t [term]
    nnoremap [term]d <cmd>Deol -split=floating -winheight=25<CR>

    " Exit deol buffer with <ESC>
    tnoremap <ESC> <cmd>quit<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = 'BufRead'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'BufRead'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = 'BufRead'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'BufRead'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'VimEnter'
hook_add = '''
    nnoremap [fugitive] <Nop>
    nmap <Space>g [fugitive]
    nnoremap [fugitive]s <cmd>Git<CR>
    nnoremap [fugitive]a <cmd>Gwrite<CR>
    nnoremap [fugitive]d <cmd>Gdiff<CR>
    nnoremap [fugitive]b <cmd>Gblame<CR>
    nnoremap [fugitive]R <cmd>Gread<CR>
    nnoremap [fugitive]c <cmd>Git commit -v<CR>
    nnoremap [fugitive]C <cmd>!git branch<CR>:Git checkout<Space>
    nnoremap [fugitive]B :Git checkout -b<Space>
    nnoremap [fugitive]D <cmd>!git branch<CR>:Git checkout -d<Space>
    nnoremap [fugitive]l <cmd>Git log<CR>
    nnoremap [fugitive]L <cmd>Git lol<CR>
    nnoremap [fugitive]t <cmd>Deol --command tig -split="floating"<CR>
    nnoremap [fugitive]M <cmd>!git branch<CR>:Git merge<Space>
    nnoremap [fugitive]m <cmd>Denite menu:fugitive_cmd<CR>
    nnoremap [fugitive]ps <cmd>Git push<CR>
    nnoremap [fugitive]pl <cmd>Git pull<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertEnter'
hook_source = '''
    source ~/dotfiles/.vim/plugins/neosnippet.vim
'''
on_ft = 'snippet'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
