[[plugins]] # Japanese localization of help
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['h', 'help']

[[plugins]] # Preview of replacement results
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]] # Translate, Japanese to English
repo = 'skanehira/translate.vim'
on_cmd = 'Translate'
hook_source = '''
    " Pop up the translated content
    let g:translate_popup_window = 1
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
    nmap <F8> :TagbarToggle<CR>
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
    source ~/dotfiles/.vim/plugins/denite.vim
'''
hook_add = '''
    nnoremap [denite] <Nop>
    nmap <Space>d [denite]
    nnoremap [denite]a <cmd>Denite file buffer file:new<CR>
    nnoremap [denite]b <cmd>Denite buffer<CR>
    nnoremap [denite]h <cmd>Denite help -start-filter<CR>
    nnoremap [denite]r <cmd>Denite register<CR>
    nnoremap [denite]g <cmd>Denite grep<CR>
    nnoremap [denite]m <cmd>Denite menu<CR>
    nnoremap [denite]dm <cmd>Denite menu:Denite_cmd<CR>
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    nnoremap [defx] <Nop>
    nmap <Space>f [defx]
    nnoremap [defx]a <cmd>Defx -search=`expand('%:p')` `expand('%:p:h')`<CR>
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/defx.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_ft = 'defx'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_ft = 'defx'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
    nnoremap [term] <Nop>
    nmap <Space>t [term]
    nnoremap [term]d <cmd>Deol -split=floating -winheight=25<CR>

    " Exit deol buffer with <ESC>
    tnoremap <ESC> <cmd>quit<CR>
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/skkeleton.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
