# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# depends = ['impatient.nvim', 'ddc.vim']
# on_ft = ['python']
# hook_source = '''
# lua << EOF
# require('lspconfig').pyright.setup{}
# EOF
# '''

# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'nvim-lspconfig'

# [[plugins]]
# repo = 'matsui54/ddc-nvim-lsp-doc'
# on_source = 'ddc-nvim-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'ddc.vim'
on_ft = ['python']
hook_source = '''
    let g:lsp_use_lua = v:true
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = 'vim-lsp'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'vim-lsp'
hook_source = '''
    source ~/dotfiles/.vim/plugins/lsp.vim
'''

[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['markdown', 'python']
hook_source = '''
    let g:ale_sign_column_always = 1
    let g:ale_linters = {
        \ 'markdown': ['textlint'],
        \ }
'''

[[plugins]]
repo = 'rhysd/vim-lsp-ale'
on_source = ['vim-lsp', 'ale']
