# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# depends = ['impatient.nvim', 'ddc.vim']
# on_ft = ['python']
# hook_source = '''
# lua << EOF
# require('lspconfig').pyright.setup{}
# EOF
# '''

# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'nvim-lspconfig'

# [[plugins]]
# repo = 'matsui54/ddc-nvim-lsp-doc'
# on_source = 'ddc-nvim-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'
depends = ['vim-lsp']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-efm-langserver-settings']
on_ft = ['python', 'markdown', 'php', 'vim']
hook_source = '''
  source ~/dotfiles/.vim/plugins/lsp.vim
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'halkn/lightline-lsp'
on_source = ['vim-lsp']
