# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# depends = ['impatient.nvim', 'ddc.vim']
# on_ft = ['python']
# hook_source = '''
# lua << EOF
# require('lspconfig').pyright.setup{}
# EOF
# '''

# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'nvim-lspconfig'

# [[plugins]]
# repo = 'matsui54/ddc-nvim-lsp-doc'
# on_source = 'ddc-nvim-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'
depends = ['vim-lsp']
hook_source = '''
" efm-langserver settings {{{

" https://github.com/nakatanakatana/dotfiles
" for efm-langserver-settings
let s:efm_args = []
if efm_langserver_settings#config_enable()
  let s:efm_args = extend(s:efm_args, ['-c', efm_langserver_settings#config_path()])
endif

let g:efm_langserver_settings#debug = 5

if efm_langserver_settings#debug_enable()
  let s:efm_args = extend(s:efm_args, ['-logfile', efm_langserver_settings#debug_path()])
  let s:efm_args = extend(s:efm_args, ['-loglevel', efm_langserver_settings#debug_enable()])
endif

let g:lsp_settings = {
  \ 'efm-langserver': {
    \ 'disabled': v:false,
    \ 'args': s:efm_args,
    \ 'allowlist': efm_langserver_settings#whitelist(),
    \ 'blocklist': efm_langserver_settings#blacklist(),
    \ }
  \ }

" }}}
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-efm-langserver-settings']
on_ft = ['python', 'markdown', 'php', 'vim']
hook_source = '''
  let g:lsp_log_file = expand('~/vim-lsp.log')
  let g:lsp_settings_enable_suggestions = 0
  "source ~/dotfiles/.vim/plugins/lsp.vim
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'halkn/lightline-lsp'
on_source = ['vim-lsp']
