snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch

  - name: git commit
    keyword: gc
    snippet: git commit

  - name: git commit --all
    keyword: gca
    snippet: git commit --all

  - name: git diff
    keyword: gd
    snippet: git diff

  - name: git push
    keyword: gps
    snippet: git push

  - name: git pull
    keyword: gpl
    snippet: git pull
