version: 2
root-markers: 
  - .git/

tools:
  textlint-lint: &textlint-lint
    prefix: textlint
    lint-command: 'textlint --format unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formas:
      - '%f-[%l:%c] %m [%terror/%r]'
    root-markers: .textlintrc
    commands: 
      - title: 'textlint fix'
      command: textlint
      arguments:
        - '--fix'
        - '${INPUT}'

languages:
  markdown:
    - <<: *textlint
