import = [
  "~/.config/alacritty/nord.toml",
  "~/.config/alacritty/keybinds/base.toml",
  "~/.config/alacritty/keybinds/os.toml",
  "~/.config/alacritty/keybinds/vi_mode.toml",
  "~/.config/alacritty/keybinds/search_mode.toml",
]

working_directory = "None"
live_config_reload = true
ipc_socket = true

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "Off"

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
