[tools]
ripgrep = "latest"
bat = "latest"
deno = "latest"
ghq = "latest"
fd = "latest"
jq = "latest"
fzf = "latest"
node = "latest"
go = "latest"
rust = "latest"
github-cli = "latest"
eza = "latest"
delta = "latest"
bun = "latest"
