name: UpdateDenoDependencies

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *" # modify to your convenient time

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Run Update Deno Dependencies
        run: deno run -A https://deno.land/x/udd/main.ts ./config/nvim/hooks/ddu/helper/deps.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(deps): update deno dependencies"
          title: Update Deno Dependencies
          body: >
            Automated updates by [deno-udd](https://github.com/hayd/deno-udd)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
