---
name: Denopendabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # modify to your convenient time

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hasundue/denopendabot@0.18.2 # @denopendabot hasundue/denopendabot
        with:
          user-token: ${{ secrets.GITHUB_TOKEN }} # needed for updating workflows
          base-branch: main
          include: "'config/nvim/hooks/ddu/deps.ts config/nvim/hooks/ddc/deps.ts config/nvim/dpp/deps.ts'"
