[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "~Search"
action = "None"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Y"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "E"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "G"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "G"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "B"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "F"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "D"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Copy"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "V"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "V"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "V"
mods = "Control"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Enter"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Z"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "F"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "F"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "T"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "T"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = ";"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = ","
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "H"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "J"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "K"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "L"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "ArrowLeft"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "ArrowDown"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "ArrowUp"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "ArrowRight"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "0"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "$"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "Home"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "End"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "^"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "H"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "M"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "L"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "B"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "E"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "%"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "/"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "?"
mods = "Shift"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "N"
mode = "Vi|~Search"
action = "None"

[[keyboard.bindings]]
key = "N"
mods = "Shift"
mode = "Vi|~Search"
action = "None"
